### ISSUE TITLE
opencc node windows安装失败

### ISSUE THREAD

**Issue by WingGao** [BYVoid/OpenCC#234]
```
npm install opencc
√ Installed 1 packages
√ Linked 1 latest versions

D:\Projs\Readed\node_modules\.1.0.5@opencc>node "E:\nvm\v7.7.2\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
  win_delay_load_hook.cc
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\BinaryDict.cpp(27): error C2589: “(”:“::”右边的非法标记 (编译源文件 ..\nod
e\binding.
cc) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\BinaryDict.cpp(27): error C2059: 语法错误:“::” (编译源文件 ..\node\binding.c
c) [D
:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\deps\darts-clone\darts.h(759): warning C4334: “<<”: 32 位移位的结果被隐式转换为
64 位(是否希
望进行 64 位移位?) (编译源文件 ..\node\binding.cc) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\deps\darts-clone\darts.h(761): warning C4319: “~”: 将“unsigned int”扩展到更大
的“Dar
ts::Details::id_type”时为零 (编译源文件 ..\node\binding.cc) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxpro
j]
D:\Projs\Readed\node_modules\.1.0.5@opencc\deps\darts-clone\darts.h(811): warning C4530: 使用了 C++ 异常处理程序，但未启用展
开语义。请指定 /E
Hsc (编译源文件 ..\node\binding.cc) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\DartsDict.cpp(138): error C2589: “(”:“::”右边的非法标记 (编译源文件 ..\nod
e\binding.
cc) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\DartsDict.cpp(138): error C2059: 语法错误:“::” (编译源文件 ..\node\binding.c
c) [D
:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\TextDict.cpp(28): error C2589: “(”:“::”右边的非法标记 (编译源文件 ..\node\
binding.cc
) [D:\Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
D:\Projs\Readed\node_modules\.1.0.5@opencc\src\TextDict.cpp(28): error C2059: 语法错误:“::” (编译源文件 ..\node\binding.cc)
 [D:\
Projs\Readed\node_modules\.1.0.5@opencc\build\binding.vcxproj]
  Copying data/config/t2s.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\t2s.json
  已复制         1 个文件。
  Copying data/config/s2t.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\s2t.json
  已复制         1 个文件。
  Copying data/config/s2twp.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\s2twp.json
  已复制         1 个文件。
  Copying data/config/s2hk.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\s2hk.json
  已复制         1 个文件。
  Copying data/config/hk2s.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\hk2s.json
  已复制         1 个文件。
  Copying data/config/tw2sp.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\tw2sp.json
  已复制         1 个文件。
  Copying data/config/t2hk.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\t2hk.json
  已复制         1 个文件。
  Copying data/config/s2tw.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\s2tw.json
  已复制         1 个文件。
  Copying data/config/tw2s.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\tw2s.json
  已复制         1 个文件。
  Copying data/config/t2tw.json to D:\Projs\Readed\node_modules\.1.0.5@opencc\build\Release\\t2tw.json
  已复制         1 个文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nvm\v7.7.2\node_modules\cnpm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\nvm\\v7.7.2\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projs\Readed\node_modules\.1.0.5@opencc
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (E:\nvm\v7.7.2\node_modules\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.26.4
npminstall args: E:\Program Files\nodejs\node.exe E:\nvm\v7.7.2\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\Sev\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org opencc
```

**Comment by gucong3000** [comment]
+1 我也是一样的问题。

**Comment by gucong3000** [comment]
我在PR #238 中为此项目添加Windows平台的CI，这样@BYVoid以后就可以第一时间发现Windows下的编译错误了。

**Comment by gucong3000** [comment]
刚才试了一下，主分支上，已可以在windows下正常安装了。
```bash
npm i -g git+git@github.com:BYVoid/OpenCC.git
```

**Comment by milu2003** [comment]
@gucong3000 弄了一天，我以为只有我有问题，原来别人也遇到问题。按照 你这个命令好像不行呀。求解决方案。

**Comment by gucong3000** [comment]
@milu2003 通过这两年死磕OpenCC，终于能正常在windows下正常编译OpenCC了。接下来我希望促成OpenCC能够在安装时免编译。

我在windows下是这样编译的:
卸载VS2005或其他版本
```bash
# 安装git
npm i -g git-win --git4win_mirror=https://npm.taobao.org/mirrors/git-for-windows
# 安装windows编译工具
npm i -g windows-build-tools --python_mirror=https://npm.taobao.org/mirrors/python/
# 安装OpenCC
npm i -g git+git@github.com:BYVoid/OpenCC.git
```
如果有其他问题，可以+我Q64272001

**Comment by milu2003** [comment]
前两条命令都没问题，第三条出错了：
```
I:\>npm i -g git+git@github.com:BYVoid/OpenCC.git
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:1
1)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:486:12)
npm WARN addRemoteGit  git+ssh://git@github.com/BYVoid/OpenCC.git resetting remo
te C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-remotes
\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c because of error: { [Error: Comma
nd failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c: Cloning into bare repository
 'C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-remotes\
ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c'...
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c: Host key verification failed
.
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c: fatal: Could not read from r
emote repository.
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c:
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c: Please make sure you have th
e correct access rights
npm ERR! git clone --template=C:\Users\Administrator.WIN-20160409UYF\AppData\Roa
ming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/BYVoid/Open
CC.git C:\Users\Administrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-rem
otes\ssh-git-github-com-BYVoid-OpenCC-git-d9b2514c: and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "git+git@github.com:BYVoid/OpenCC.g
it"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Ad
ministrator.WIN-20160409UYF\AppData\Roaming\npm-cache\_git-remotes\_templates --
mirror ssh://git@github.com/BYVoid/OpenCC.git C:\Users\Administrator.WIN-2016040
9UYF\AppData\Roaming\npm-cache\_git-remotes\ssh-git-github-com-BYVoid-OpenCC-git
-d9b2514c
npm ERR! Cloning into bare repository 'C:\Users\Administrator.WIN-20160409UYF\Ap
pData\Roaming\npm-cache\_git-remotes\ssh-git-github-com-BYVoid-OpenCC-git-d9b251
4c'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     I:\npm-debug.log

I:\>
```

**Comment by gucong3000** [comment]
git提示你无权限访问这个仓库呢，要不你在这个项目首页用浏览器下载整个项目的zip压缩包到本地解压吧。解压后，进入一级目录，命令行运行npm l

**Comment by milu2003** [comment]
@gucong3000 通过git安装是因为还没同步到npm吗

**Comment by milu2003** [comment]
npm l 没有这个命令吧？运行直接提示没有这个命令。

**Comment by milu2003** [comment]
@gucong3000 不搞了。如果源码有问题，我怎么搞都是浪费时间 。还是希望作者能更新一下吧。像你这样折腾两年就没必要了。

我目前使用其他替代品了。目前没发现有任何问题，可能效果会打点折扣，但在可以接受范围内。
日后这个项目解决这个问题再切换回来。感谢你的热心帮助。

**Comment by gucong3000** [comment]
是的，作者还未发布到npm上，前面写的`npm I`是写错了，正确的是`npm i`
