### ISSUE TITLE
v1.1.1 cannot run on docker( v1.1.0 works well)

### ISSUE THREAD

**Issue by DamonJiang** [BYVoid/OpenCC#420]
official python docker (version 3.7), installed successfully but got this error when init it:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/opencc/__init__.py", line 44, in <module>
    libopencc = CDLL(_libopenccfile, use_errno=True)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.7/site-packages/opencc/clib/lib/libopencc.so.1.1)

**Comment by sgalal** [comment]
Fixed #419
