### ISSUE TITLE
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by Monster-DP** [BYVoid/OpenCC#588]
C:\Users\木羊羽\AppData\Local\Programs\Python\Python39\python.exe D:/Multifarious/Python/测试.py
Traceback (most recent call last):
  File "D:\Multifarious\Python\测试.py", line 3, in <module>
    converter.convert('汉字')  # 漢字
  File "C:\Users\木羊羽\AppData\Local\Programs\Python\Python39\lib\site-packages\opencc\__init__.py", line 87, in convert
    retv_i = libopencc.opencc_convert_utf8(self._od, text, len(text))
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
Exception ignored in: <function OpenCC.__del__ at 0x0000029D97A14430>
Traceback (most recent call last):
  File "C:\Users\木羊羽\AppData\Local\Programs\Python\Python39\lib\site-packages\opencc\__init__.py", line 99, in __del__
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by z16166** [comment]
我这里用最新版的main分支的代码编译出来的lib也是这个错误，用C++、C调用都是这个错误。

**Comment by huangxin168** [comment]
我的沥青款类似，如果opencc库安装到中文路径，调用的时候
libopencc.opencc_close(self._od)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by huangxin168** [comment]
> 我这里用最新版的main分支的代码编译出来的lib也是这个错误，用C++、C调用都是这个错误。
> 
> 原因是不能只有一个s2t.json文件，这个文件目录下的其他文件比如STPhrases.ocd2也是需要的。

原因是opencc库安装到中文路径

**Comment by frankslin** [comment]
這是中文路徑支持的問題，新版本應已解決。 https://github.com/BYVoid/OpenCC/issues/1101
