### ISSUE TITLE
“npm install opencc” can't work

### ISSUE THREAD

**Issue by Cobb-Zhang** [BYVoid/OpenCC#614]
`129 error code 1
130 error path D:\FineReport\nodeApps\app1\node_modules\opencc
131 error command failed
132 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild
133 error Failed to execute 'D:\node\nodejs\node.exe D:\node\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release\opencc.node --module_name=opencc --module_path=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
133 error Failed to execute 'D:\node\nodejs\node.exe D:\node\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --module=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release\opencc.node --module_name=opencc --module_path=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
134 error node-pre-gyp info it worked if it ends with ok
134 error node-pre-gyp info using node-pre-gyp@0.14.0
134 error node-pre-gyp info using node@14.16.0 | win32 | x64
134 error node-pre-gyp WARN Using needle for node-pre-gyp https download
134 error node-pre-gyp info check checked for "D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release\opencc.node" (not found)
134 error node-pre-gyp http GET https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v83-win32-x64.tar.gz
134 error node-pre-gyp WARN download ignoring invalid "proxy" config setting: "127.0.0.1:7890"
134 error node-pre-gyp http 404 https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v83-win32-x64.tar.gz
134 error node-pre-gyp WARN Tried to download(404): https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v83-win32-x64.tar.gz
134 error node-pre-gyp WARN Pre-built binaries not found for opencc@1.1.3 and node@14.16.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
134 error node-pre-gyp http 404 status code downloading tarball https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v83-win32-x64.tar.gz
134 error gyp info it worked if it ends with ok
134 error gyp info using node-gyp@7.1.2
134 error gyp info using node@14.16.0 | win32 | x64
134 error gyp info ok
134 error gyp info it worked if it ends with ok
134 error gyp info using node-gyp@7.1.2
134 error gyp info using node@14.16.0 | win32 | x64
134 error gyp info find Python using Python version 3.6.6 found at "C:\Program Files\python\python.exe"
134 error gyp http GET https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
134 error gyp WARN download ignoring invalid "proxy" config setting: "127.0.0.1:7890"
134 error gyp WARN install got an error, rolling back install
134 error gyp ERR! configure error
134 error gyp ERR! stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 7890
134 error gyp ERR! stack     at ClientRequest.onError (D:\node\nodejs\node_global\node_modules\npm\node_modules\tunnel-agent\index.js:177:17)
134 error gyp ERR! stack     at Object.onceWrapper (events.js:422:26)
134 error gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
134 error gyp ERR! stack     at Socket.socketErrorListener (_http_client.js:469:9)
134 error gyp ERR! stack     at Socket.emit (events.js:315:20)
134 error gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
134 error gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
134 error gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
134 error gyp ERR! System Windows_NT 10.0.19042
134 error gyp ERR! command "D:\\node\\nodejs\\node.exe" "D:\\node\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\build\\Release\\opencc.node" "--module_name=opencc" "--module_path=D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
134 error gyp ERR! cwd D:\FineReport\nodeApps\app1\node_modules\opencc
134 error gyp ERR! node -v v14.16.0
134 error gyp ERR! node-gyp -v v7.1.2
134 error gyp ERR! not ok
134 error node-pre-gyp ERR! build error
134 error node-pre-gyp ERR! stack Error: Failed to execute 'D:\node\nodejs\node.exe D:\node\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release\opencc.node --module_name=opencc --module_path=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
134 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\FineReport\nodeApps\app1\node_modules\opencc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
134 error node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
134 error node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
134 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
134 error node-pre-gyp ERR! System Windows_NT 10.0.19042
134 error node-pre-gyp ERR! command "D:\\node\\nodejs\\node.exe" "D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
134 error node-pre-gyp ERR! cwd D:\FineReport\nodeApps\app1\node_modules\opencc
134 error node-pre-gyp ERR! node -v v14.16.0
134 error node-pre-gyp ERR! node-pre-gyp -v v0.14.0
134 error node-pre-gyp ERR! not ok
134 error node-pre-gyp info it worked if it ends with ok
134 error node-pre-gyp info using node-pre-gyp@0.14.0
134 error node-pre-gyp info using node@14.16.0 | win32 | x64
134 error gyp info it worked if it ends with ok
134 error gyp info using node-gyp@7.1.2
134 error gyp info using node@14.16.0 | win32 | x64
134 error gyp info ok
134 error gyp info it worked if it ends with ok
134 error gyp info using node-gyp@7.1.2
134 error gyp info using node@14.16.0 | win32 | x64
134 error gyp info find Python using Python version 3.6.6 found at "C:\Program Files\python\python.exe"
134 error gyp http GET https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
134 error gyp WARN download ignoring invalid "proxy" config setting: "127.0.0.1:7890"
134 error gyp WARN install got an error, rolling back install
134 error gyp ERR! configure error
134 error gyp ERR! stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 7890
134 error gyp ERR! stack     at ClientRequest.onError (D:\node\nodejs\node_global\node_modules\npm\node_modules\tunnel-agent\index.js:177:17)
134 error gyp ERR! stack     at Object.onceWrapper (events.js:422:26)
134 error gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
134 error gyp ERR! stack     at Socket.socketErrorListener (_http_client.js:469:9)
134 error gyp ERR! stack     at Socket.emit (events.js:315:20)
134 error gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
134 error gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
134 error gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
134 error gyp ERR! System Windows_NT 10.0.19042
134 error gyp ERR! command "D:\\node\\nodejs\\node.exe" "D:\\node\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--module=D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\build\\Release\\opencc.node" "--module_name=opencc" "--module_path=D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
134 error gyp ERR! cwd D:\FineReport\nodeApps\app1\node_modules\opencc
134 error gyp ERR! node -v v14.16.0
134 error gyp ERR! node-gyp -v v7.1.2
134 error gyp ERR! not ok
134 error node-pre-gyp ERR! build error
134 error node-pre-gyp ERR! stack Error: Failed to execute 'D:\node\nodejs\node.exe D:\node\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --module=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release\opencc.node --module_name=opencc --module_path=D:\FineReport\nodeApps\app1\node_modules\opencc\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
134 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\FineReport\nodeApps\app1\node_modules\opencc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
134 error node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
134 error node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
134 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
134 error node-pre-gyp ERR! System Windows_NT 10.0.19042
134 error node-pre-gyp ERR! command "D:\\node\\nodejs\\node.exe" "D:\\FineReport\\nodeApps\\app1\\node_modules\\opencc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild"
134 error node-pre-gyp ERR! cwd D:\FineReport\nodeApps\app1\node_modules\opencc
134 error node-pre-gyp ERR! node -v v14.16.0
134 error node-pre-gyp ERR! node-pre-gyp -v v0.14.0
134 error node-pre-gyp ERR! not ok
135 verbose exit 1
`

**Comment by BYVoid** [comment]
Please paste the error.

**Comment by dicky1126277766238** [comment]
> Please paste the error.

Here is mine

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated url-regex-safe@1.1.0: Please upgrade to url-regex-safe@v3.0.0+ AND install re2 as an additional dependency in your project via `npm install re2` or `yarn add re2`.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated ts-custom-error@2.2.2: npm package tarball contains useless codeclimate-reporter binary, please update to version 3.1.1. See https://github.com/adriengibrat/ts-custom-error/issues/32
npm ERR! code 1
npm ERR! path /home/ubuntu/project/node_modules/opencc
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild
npm ERR! make: Entering directory '/home/ubuntu/project/node_modules/opencc/build'
npm ERR!   COPY Release/hk2s.json
npm ERR!   COPY Release/hk2t.json
npm ERR!   COPY Release/jp2t.json
npm ERR!   COPY Release/s2hk.json
npm ERR!   COPY Release/s2t.json
npm ERR!   COPY Release/s2tw.json
npm ERR!   COPY Release/s2twp.json
npm ERR!   COPY Release/t2hk.json
npm ERR!   COPY Release/t2jp.json
npm ERR!   COPY Release/t2s.json
npm ERR!   COPY Release/t2tw.json
npm ERR!   COPY Release/tw2s.json
npm ERR!   COPY Release/tw2sp.json
npm ERR!   COPY Release/tw2t.json
npm ERR!   TOUCH Release/obj.target/configs.stamp
npm ERR!   CXX(target) Release/obj.target/opencc/node/marisa.o
npm ERR! make: Leaving directory '/home/ubuntu/project/node_modules/opencc/build'
npm ERR! Failed to execute '/home/ubuntu/node16/bin/node /home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/home/ubuntu/project/node_modules/opencc/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! [opencc] Removing "/home/ubuntu/project/node_modules/opencc/build/Release"
npm ERR! make: Entering directory '/home/ubuntu/project/node_modules/opencc/build'
npm ERR!   COPY Release/hk2s.json
npm ERR!   COPY Release/hk2t.json
npm ERR!   COPY Release/jp2t.json
npm ERR!   COPY Release/s2hk.json
npm ERR!   COPY Release/s2t.json
npm ERR!   COPY Release/s2tw.json
npm ERR!   COPY Release/s2twp.json
npm ERR!   COPY Release/t2hk.json
npm ERR!   COPY Release/t2jp.json
npm ERR!   COPY Release/t2s.json
npm ERR!   COPY Release/t2tw.json
npm ERR!   COPY Release/tw2s.json
npm ERR!   COPY Release/tw2sp.json
npm ERR!   COPY Release/tw2t.json
npm ERR!   TOUCH Release/obj.target/configs.stamp
npm ERR!   CXX(target) Release/obj.target/opencc/node/marisa.o
npm ERR! make: Leaving directory '/home/ubuntu/project/node_modules/opencc/build'
npm ERR! Failed to execute '/home/ubuntu/node16/bin/node /home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/home/ubuntu/project/node_modules/opencc/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@16.13.2 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for opencc@1.1.3 and node@16.13.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/BYVoid/OpenCC/releases/download/1.1.3/opencc-v1.1.3-node-v93-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/project/node_modules/opencc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project/node_modules/opencc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: Command not found
npm ERR! make: *** [opencc.target.mk:126: Release/obj.target/opencc/node/marisa.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.11.0-1022-aws
npm ERR! gyp ERR! command "/home/ubuntu/node16/bin/node" "/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node" "--module_name=opencc" "--module_path=/home/ubuntu/project/node_modules/opencc/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/ubuntu/project/node_modules/opencc
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/node16/bin/node /home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/home/ubuntu/project/node_modules/opencc/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.11.0-1022-aws
npm ERR! node-pre-gyp ERR! command "/home/ubuntu/node16/bin/node" "/home/ubuntu/project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/ubuntu/project/node_modules/opencc
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/project/node_modules/opencc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project/node_modules/opencc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: Command not found
npm ERR! make: *** [opencc.target.mk:126: Release/obj.target/opencc/node/marisa.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.11.0-1022-aws
npm ERR! gyp ERR! command "/home/ubuntu/node16/bin/node" "/home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node" "--module_name=opencc" "--module_path=/home/ubuntu/project/node_modules/opencc/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/ubuntu/project/node_modules/opencc
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/node16/bin/node /home/ubuntu/node16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/ubuntu/project/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/home/ubuntu/project/node_modules/opencc/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.11.0-1022-aws
npm ERR! node-pre-gyp ERR! command "/home/ubuntu/node16/bin/node" "/home/ubuntu/project/node_modules/.bin/node-pre-gyp" "rebuild"
npm ERR! node-pre-gyp ERR! cwd /home/ubuntu/project/node_modules/opencc
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-01-28T11_29_55_598Z-debug-0.log

**Comment by 307590317** [comment]
I met the same problem, but I was using yarn 14.17.5

**Comment by zijianhuang** [comment]
It seems the installation needs Python and Visual C++ installed on Windows.

```
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2022 (17.2.32526.322) found at:
npm ERR! gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Professional"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - missing any VC++ toolset
npm ERR! gyp ERR! find VS checking VS2019 (16.11.31702.278) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - missing any VC++ toolset
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

```

And apparently this needs to be fixed too:
```
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
```

**Comment by zijianhuang** [comment]
However, after installing VS C++, more errors appear since the installation tried to rebuild the whole opencc missing a lot dependencies. After all, requiring rebuild is not looking good.

**Comment by mingyigg** [comment]
碰到同样的问题，在mac上

**Comment by lukelu0520** [comment]
Great library but we also get the same issue on AWS server using Ubuntu 20.04, Node 14.18.2, gcc 10. Hope there are more instructions about Node with cloud server.

**Comment by JackWong0303** [comment]
Don't spend time on installing this package on windows anymore. For windows users, I suggest you to install `wsl` in your machine and use Linux environment to run your code.

My Linux Environment:
Ubuntu 20.04 LTS

I installed the following packages:
gcc 10
npm 8.1.3
node 14
python 3.8

**Comment by tx0c** [comment]
hit similar problem on `Ubuntu 22.04.1 LTS`:  it found `python3` and says use that but somewhere later still errors `python` not found:

    npm ERR! gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
    [...]
    npm ERR! /bin/sh: 1: python: not found

it seems to be a convention /usr/bin/python means python2, and it's no longer installed by default, then I installed a small `python-is-python3` package to provide a symlink `/usr/bin/python -> python3`

    # apt install python-is-python3

and then `npm install opencc` succeeded.    manual creation of the symlink should also work

**Comment by hesetiema** [comment]
mark

**Comment by zp-huang** [comment]
npm install opencc-js  worked

**Comment by zp-huang** [comment]
https://www.npmjs.com/package/opencc-js

**Comment by latel** [comment]
> 在mac上碰到同样的问题，这个工具需要预先安装什么依赖或者工具能否在文档里说明一下？

brew install cmake doxygen

**Comment by frankslin** [comment]
OpenCC will start providing prebuilt binaries starting from the next minor release (1.3.1).
