### ISSUE TITLE
Win7下pip install出現UnicodeDecodeError問題

### ISSUE THREAD

**Issue by morsanga** [BYVoid/OpenCC#729]
您好

我於Win7下使用**pip install opencc**安裝後會出現以下問題

```
Collecting opencc
  Using cached OpenCC-0.2.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × **python setup.py egg_info did not run successfully**.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Home\AppData\Local\Temp\pip-install-7d8qvzwm\opencc_aa6c6
1a3d63b4119ab6aa1fb6e2a4567\setup.py", line 19, in <module>
          long_description=fread('README.rst'),
        File "C:\Users\Home\AppData\Local\Temp\pip-install-7d8qvzwm\opencc_aa6c6
1a3d63b4119ab6aa1fb6e2a4567\setup.py", line 10, in fread
          return f.read()
      **UnicodeDecodeError: 'cp950' codec can't decode byte 0x9d in position 458**:
illegal multibyte sequence
      [end of output]
```

以下為版本資訊：
Python：3.7.3
pip：22.3
setuptools：65.5.0

已試過更新pip、setuptools版本，但仍然出現一樣的問題.....
請問該怎麼處理呢？
感謝感謝orz

**Comment by BYVoid** [comment]
轉換的原始文本必須是UTF-8純文本。
