### ISSUE TITLE
OSError on import opencc 

### ISSUE THREAD

**Issue by danushk97** [BYVoid/OpenCC#784]
Getting OSError on import opencc. 

Environment details:
OS: MacOS Ventura 13.3.1
Python 3.10.9

>>> import opencc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danush/anaconda3/envs/test_env/lib/python3.10/site-packages/opencc.py", line 24, in <module>
    libopencc = CDLL('libopencc.so.1', use_errno=True)
  File "/Users/danush/anaconda3/envs/test_env/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libopencc.so.1, 0x0006): tried: 'libopencc.so.1' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibopencc.so.1' (no such file), '/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/Users/danush/anaconda3/envs/test_env/lib/python3.10/lib-dynload/../../libopencc.so.1' (no such file), '/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/danush/anaconda3/envs/test_env/lib/libopencc.so.1' (no such file), '/Users/danush/anaconda3/envs/test_env/bin/../lib/libopencc.so.1' (no such file), '/usr/lib/libopencc.so.1' (no such file, not in dyld cache), 'libopencc.so.1' (no such file), '/usr/local/lib/libopencc.so.1' (no such file), '/usr/lib/libopencc.so.1' (no such file, not in dyld cache)

**Comment by yellowgraysu** [comment]
Look similar to the issue https://github.com/BYVoid/OpenCC/issues/759

If you using Python, you can try the pure Python version to support the macOS M1(Apple Silicon) https://github.com/yichen0831/opencc-python

**Comment by frankslin** [comment]
https://pypi.org/project/OpenCC/1.3.1/ 應已解決。
